[web]
Listen = ":8080"
Fasthttp = false

[lib]
CallAPI = true

[db]
Driver = "mysql"
User = "root"
Passwd = "rocky"
Host = "127.0.0.1:3306"
DBName = "tel_info"

[log]
Mode = "file"
Level = "trace"
Buffer = 100000

FileName = "log.log"
LogRotate = true
MaxLines = 10000
MaxSizeShift = 28
DailyRotate = true
MaxDays = 7


[pongo]
Directory = "src/views"
Reload = true